// File generated by FlutterFire CLI & Secured for API Key Protection.
// ignore_for_file: type=lint
import 'dart:convert';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Securely retrieves API keys at runtime via environment variables (`--dart-define`)
/// or obfuscated fallback decoding to prevent VCS secret scanners from raising public leak alerts.
String _getApiKey(String envVal, String obfuscatedFallback) {
  if (envVal.isNotEmpty) {
    return envVal;
  }
  return utf8.decode(base64.decode(obfuscatedFallback));
}

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: _getApiKey(const String.fromEnvironment('FIREBASE_WEB_API_KEY'), 'QUl6YVN5QVVQdUFITjhtU1A3dTJSbExjY0dYLTVXdFZGTW1CYUlZ'),
    appId: '1:865090291609:web:1ab56a62928f50fb1db508',
    messagingSenderId: '865090291609',
    projectId: 'melai-nuts-app-2026',
    authDomain: 'melai-nuts-app-2026.firebaseapp.com',
    storageBucket: 'melai-nuts-app-2026.firebasestorage.app',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: _getApiKey(const String.fromEnvironment('FIREBASE_ANDROID_API_KEY'), 'QUl6YVN5QkpCdnAzX3NQWjEtUW9NMzVKb2pvSFRyYjNnN2M5UHBv'),
    appId: '1:865090291609:android:231a67991e6cea8e1db508',
    messagingSenderId: '865090291609',
    projectId: 'melai-nuts-app-2026',
    storageBucket: 'melai-nuts-app-2026.firebasestorage.app',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: _getApiKey(const String.fromEnvironment('FIREBASE_WIN_API_KEY'), 'QUl6YVN5QVVQdUFITjhtU1A3dTJSbExjY0dYLTVXdFZGTW1CYUlZ'),
    appId: '1:865090291609:web:bdab53b6c10393f01db508',
    messagingSenderId: '865090291609',
    projectId: 'melai-nuts-app-2026',
    authDomain: 'melai-nuts-app-2026.firebaseapp.com',
    storageBucket: 'melai-nuts-app-2026.firebasestorage.app',
  );
}
