// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUPuAHN8mSP7u2RlLccGX-5WtVFMmBaIY',
    appId: '1:865090291609:web:1ab56a62928f50fb1db508',
    messagingSenderId: '865090291609',
    projectId: 'melai-nuts-app-2026',
    authDomain: 'melai-nuts-app-2026.firebaseapp.com',
    storageBucket: 'melai-nuts-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJcvp3_sPZ1-QoM35JojoHTrb3g7c9Ppo',
    appId: '1:865090291609:android:231a67991e6cea8e1db508',
    messagingSenderId: '865090291609',
    projectId: 'melai-nuts-app-2026',
    storageBucket: 'melai-nuts-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUPuAHN8mSP7u2RlLccGX-5WtVFMmBaIY',
    appId: '1:865090291609:web:bdab53b6c10393f01db508',
    messagingSenderId: '865090291609',
    projectId: 'melai-nuts-app-2026',
    authDomain: 'melai-nuts-app-2026.firebaseapp.com',
    storageBucket: 'melai-nuts-app-2026.firebasestorage.app',
  );
}
